-- Part A – Intermediate JOIN + GROUP BY
-- Q1.
-- Display each customer's total number of products purchased. Use: JOIN, SUM(quantity)
select sum(od.quantity),c.customer_name 
from order_details od
join orders o
on od.order_id = o.order_id
join customers c
on o.customer_id = c.customer_id
group by c.customer_name ;

-- Q2.
-- Display each customer's total spending. Use: JOIN, SUM(quantity × price)
select sum(od.quantity * p.price),c.customer_name 
from order_details od
join orders o
on od.order_id = o.order_id
join customers c
on o.customer_id = c.customer_id
join products p
on od.product_id = p.product_id
group by c.customer_name ;

-- Q3.
-- Display the top 5 products based on revenue. Use: JOIN, SUM(), ORDER BY
select sum(od.quantity * p.price) , p.product_name 
from order_details od
join products p
on od.product_id = p.product_id
group by p.product_name
order by sum(od.quantity * p.price) desc 
limit 5;

-- Q4.
-- Display the least-selling product. Use: SUM(quantity), ORDER BY
select sum(od.quantity ) , p.product_name 
from order_details od
join products p
on od.product_id = p.product_id
group by p.product_name
order by sum(od.quantity) 
limit 1;


-- Q5.
-- Display each category with its average product price and maximum product price. Use: AVG(), MAX()
select avg(p.price) as average_product_price ,max(p.price) as maximum_product_price , c.category_name 
from products p
join categories c
on p.category_id = c.category_id
group by category_name;

-- Q6.
-- Display the customer who placed the highest number of orders. Use: COUNT(), ORDER BY
select count(o.order_id),c.customer_name 
from order_details od
join orders o
on od.order_id = o.order_id
join customers c
on o.customer_id = c.customer_id
group by c.customer_name 
order by count(o.order_id) desc
limit 1;

-- Q7.
-- Display the total revenue generated by each category. Use: JOIN, SUM(quantity × price)
select sum(od.quantity * p.price),c.category_name 
from order_details od
join products p
on od.product_id = p.product_id 
join categories c
on p.category_id = c.category_id 
group by c.category_name;

-- Q8.
-- Display all customers whose total spending is greater than the average customer spending.
-- ⚠️ Use: GROUP BY
-- Hint: First calculate spending for each customer, then compare it. (You may solve this after learning subqueries if needed.)
SELECT
    c.customer_id,
    c.customer_name,
    SUM(od.quantity * p.price) AS total_spending
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_details od
    ON o.order_id = od.order_id
JOIN products p
    ON od.product_id = p.product_id
GROUP BY c.customer_id, c.customer_name
HAVING SUM(od.quantity * p.price) >
(
    SELECT AVG(customer_spending)
    FROM
    (
        SELECT
            SUM(od.quantity * p.price) AS customer_spending
        FROM customers c
        JOIN orders o
            ON c.customer_id = o.customer_id
        JOIN order_details od
            ON o.order_id = od.order_id
        JOIN products p
            ON od.product_id = p.product_id
        GROUP BY c.customer_id
    ) AS spending
);
-- Q9.
-- Display the top 3 categories based on revenue.
select sum(od.quantity * p.price),c.category_name 
from order_details od
join products p
on od.product_id = p.product_id 
join categories c
on p.category_id = c.category_id 
group by c.category_name
order by  sum(od.quantity * p.price) desc
limit 3;


-- Q10.
-- Display the customer who purchased the highest quantity of products.
select sum(od.quantity),c.customer_name 
from order_details od
join orders o
on od.order_id = o.order_id
join customers c
on o.customer_id = c.customer_id
group by c.customer_name 
order by sum(od.quantity) desc
limit 1;



-- Part B – Business Scenario Questions
-- Q11.
-- Display the number of different products ordered by each customer.
-- Use: COUNT(DISTINCT product_id)
select count(distinct p.product_id),c.customer_name 
from order_details od
join orders o
on od.order_id = o.order_id
join customers c
on o.customer_id = c.customer_id
join products p
on od.product_id = p.product_id
group by c.customer_name ;


-- Q12.
-- Display the average quantity per order.
select round(avg(quantity),1) , order_id 
from order_details 
group by order_id;

-- Q13.
-- Display the order having the highest total amount.
select sum(od.quantity*p.price) , od.order_id
from order_details od
join products p
on od.product_id = p.product_id
group by od.order_id
order by  sum(od.quantity*p.price) desc
limit 1;

-- Q14.
-- Display all products whose total sales quantity is greater than 10.
-- Use: HAVING
select sum(od.quantity) , p.product_name 
from order_details od
join products p
on od.product_id = p.product_id
group by p.product_name
having sum(od.quantity) > 10;

-- Q15.
-- Display the number of orders placed by each city.
select count(o.order_id) , c.city
from orders o
join customers c
on o.customer_id = c.customer_id 
group by c.city;

-- Q16.
-- Display the city with the highest revenue.
select sum(od.quantity*p.price) , c.city
from orders o
join customers c
on o.customer_id = c.customer_id 
join order_details od 
on od.order_id = o.order_id 
join products p
on od.product_id = p.product_id 
group by c.city
order by sum(od.quantity*p.price) desc
limit 1;

-- Q17.
-- Display customers who purchased at least 3 different products.
-- Use: COUNT(DISTINCT product_id)
select count(distinct p.product_id) , c.customer_name 
from orders o
join customers c
on o.customer_id = c.customer_id 
join order_details od 
on od.order_id = o.order_id 
join products p
on od.product_id = p.product_id
group by c.customer_name 
having count(distinct p.product_id)>=3;

-- Q18.
-- Display each category's total products and total revenue.
select count(distinct p.product_id) as total_products  , sum(od.quantity*p.price) as total_revenue , cg.category_name 
from orders o
join customers c
on o.customer_id = c.customer_id 
join order_details od 
on od.order_id = o.order_id 
join products p
on od.product_id = p.product_id
join categories cg
on p.category_id = cg.category_id
group by cg.category_name 
-- Q19.
-- Display the top 5 customers based on total quantity purchased.
select sum(od.quantity) as total_quantity ,c.customer_name 
from order_details od
join orders o
on od.order_id = o.order_id
join customers c
on o.customer_id = c.customer_id
group by c.customer_name 
order by sum(od.quantity) desc
limit 5;

-- Q20.
-- Display the overall revenue generated by all orders.
select sum(od.quantity * p.price) as total_revenue
from order_details od
join orders o
on od.order_id = o.order_id
join customers c
on o.customer_id = c.customer_id
join products p
on od.product_id = p.product_id;
