-- Basic JOINs
-- Q1
-- Display the customer ID, customer city, and order ID for every order.
-- Use customers and orders.
select c.customer_id , c.customer_city ,o.order_id
from customers c
join orders o
on c.customer_id = o.customer_id;

-- Q2
-- Display:
-- order_id
-- customer_id
-- order_status
-- customer_city
-- customer_state
-- for all orders.
select o.order_id , c.customer_id ,o.order_status ,c.customer_city,c.customer_state
from orders o
join customers c
on o.customer_id = c.customer_id;

-- Q3
-- Display each order item along with the product category name.
-- Show:
-- order_id
-- product_id
-- price
-- product_category_name
select oi.order_id , p.product_id , oi.price , p.product_category_name
from order_items oi
join products p
on oi.product_id = p.product_id;

-- Q4
-- Display each order item along with the seller's city and state.
-- Show:
-- order_id
-- product_id
-- seller_id
-- seller_city
-- seller_state
select oi.order_id , oi.product_id , s.seller_id , s.seller_city , s.seller_state
from order_items oi
join sellers s
on oi.seller_id = s.seller_id;

-- Q5
-- Display all orders along with their payment type and payment value.
-- Show:
-- order_id
-- order_status
-- payment_type
-- payment_value
select o.order_id , o.order_status , op.payment_type , op.payment_value
from orders o
join order_payments op
on o.order_id = op.order_id;

-- 🟡 JOIN + WHERE
-- Q6
-- Find all delivered orders along with:
-- order_id
-- customer_id
-- customer_city
-- customer_state
select o.order_id , o.order_status , c.customer_id , c.customer_city , c.customer_state
from orders o
join customers c
on o.customer_id = c.customer_id
where o.order_status = 'delivered';

-- Q7
-- Find all order items for products belonging to the category:
-- bed_bath_table
-- Display:
-- order_id
-- product_id
-- price
-- product_category_name
select oi.order_id , p.product_id , oi.price , p.product_category_name
from order_items oi
join products p
on oi.product_id = p.product_id 
where p.product_category_name = 'bed_bath_table';
-- Q8
-- Find all orders placed by customers from São Paulo (SP).
-- Display:
-- order_id
-- customer_id
-- customer_city
-- order_status
select o.order_id ,c.customer_id , c.customer_city , o.order_status
from orders o
join customers c
on o.customer_id = c.customer_id 
where c.customer_state = 'SP';

-- Q9
-- Find all products sold by sellers from SP.
-- Display:
-- product_id
-- seller_id
-- seller_city
-- seller_state
select oi.product_id , s.seller_id , s.seller_city , s.seller_state
from order_items oi
join sellers s
on oi.seller_id = s.seller_id
where s.seller_state = 'SP';

-- 🟠 JOIN + GROUP BY
-- Q10
-- Find the number of orders placed by customers in each state.
-- Display:
-- customer_state
-- order_count
-- Sort from highest to lowest.
select count(o.order_id) as order_count , c.customer_state 
from orders o
join customers c
on o.customer_id = c.customer_id
group by c.customer_state
order by order_count desc;

-- Q11
-- Find the total sales generated by each product category.
-- Use price from order_items.
-- Display:
-- product_category_name
-- total_sales
-- Sort highest to lowest.
select sum(oi.price) as total_sales , p.product_category_name
from order_items oi
join products p
on oi.product_id = p.product_id
group by p.product_category_name
order by total_sales desc;

-- Q12
-- Find the total freight value generated by sellers in each state.
-- Display:
-- seller_state
-- total_freight
select sum(oi.freight_value) as total_freight , s.seller_state
from order_items oi
join sellers s
on oi.seller_id = s.seller_id
group by s.seller_state
order by total_freight desc;

-- Q13
-- Find the average order-item price for each product category.
-- Display:
-- product_category_name
-- average_price
-- Sort highest to lowest.
select round(avg(oi.price)) as avgerage_price , p.product_category_name
from order_items oi
join products p
on oi.product_id = p.product_id 
group by p.product_category_name
order by avgerage_price desc;


-- Q14
-- Find the number of order items sold by each seller.
-- Display:
-- seller_id
-- seller_city
-- items_sold
-- Sort highest to lowest.
-- Remember: there is no quantity column, so use COUNT(*).
select s.seller_id , s.seller_city , count(oi.order_id) as item_sold
from order_items oi
join sellers s
on oi.seller_id = s.seller_id
group by s.seller_id , s.seller_city
order by item_sold desc;

-- 🔥 Multi-table JOINs
-- Q15
-- Find the top 10 customer cities by total spending.
-- Use:
-- customers → orders → order_items
-- Calculate total spending using:
-- SUM(price)
-- Display:
-- customer_city
-- total_spending
select sum(oi.price) as total_spending ,c.customer_city
from order_items oi
join orders o
on oi.order_id = o.order_id 
join customers c
on o.customer_id = c.customer_id
group by c.customer_city
order by total_spending desc
limit 10;

-- Q16
-- Find the top 10 product categories by total sales.
-- Use:
-- products → order_items
-- Display:
-- product_category_name
-- total_sales
select sum(oi.price) as total_sales , p.product_category_name
from order_items oi
join products p
on oi.product_id = p.product_id
group by p.product_category_name 
order by total_sales desc
limit 10;

-- Q17
-- Find the number of delivered orders for each customer state.
-- Use:
-- customers → orders
-- Display:
-- customer_state
-- delivered_orders
-- Sort highest to lowest.
select count(o.order_id) as delivered_order , c.customer_state
from orders o
join customers c
on o.customer_id = c.customer_id
where o.order_status = 'delivered'
group by c.customer_state
order by delivered_order desc;

-- Q18
-- Find the average review score for each product category.
-- You'll need:
-- order_reviews → order_items → products
-- Display:
-- product_category_name
-- average_review_score
-- Sort highest to lowest.
select round(avg(ov.review_score),1) as average_review_score , p.product_category_name
from order_reviews ov
join order_items oi
on ov.order_id = oi.order_id
join products p
on oi.product_id = p.product_id
group by p.product_category_name 
order by average_review_score desc;

-- Q19 🔥
-- Find the top 10 sellers by total sales.
-- Use:
-- order_items → sellers
-- Display:
-- seller_id
-- seller_city
-- seller_state
-- total_sales
-- Sort highest to lowest.
select sum(oi.price) as total_sales , s.seller_id , s.seller_city ,s.seller_state 
from order_items oi
join sellers s
on oi.seller_id = s.seller_id
group by s.seller_id , s.seller_city , s.seller_state
order by total_sales desc
limit 10;

-- Q20 🔥 Challenge
-- Find the top 10 customer states by total payment value.
-- You'll need:
-- customers → orders → order_payments
-- Display:
-- customer_state
-- total_payment
-- Sort from highest to lowest.
select sum(op.payment_value) as total_payment , c.customer_state
from order_payments op
join orders o
on op.order_id = o.order_id 
join customers c
on o.customer_id = c.customer_id
group by c.customer_state
order by total_payment desc
limit 10;
