-- Part A – CASE WHEN (15 Questions)
-- Q1.
-- Display each product with a new column Price_Category:
-- Price ≥ 5000 → 'Expensive'
-- Otherwise → 'Affordable'
SELECT PRODUCT_NAME , PRICE ,
CASE
     WHEN PRICE >= 5000 THEN 'EXPENSIVE'
	 ELSE 'AFFORDABLE'
	 END AS PRICE_CATEGORY
FROM PRODUCTS;

-- Q2.
-- Display each customer with a new column Customer_Type:
-- City = 'Pune' → 'Local'
-- Otherwise → 'Outside Pune'
SELECT CUSTOMER_NAME , CITY ,
CASE 
   WHEN CITY = 'Pune' THEN 'LOCAL'
   ELSE 'OUTSIDE PUNE'
   END AS CUSTOMER_TYPE
FROM CUSTOMERS;

-- Q3.
-- Display each order with a new column Order_Status:
-- Order date before 2024-04-01 → 'Old Order'
-- Otherwise → 'New Order'
SELECT ORDER_ID , ORDER_DATE ,
CASE 
    WHEN ORDER_DATE < '2024-04-01' THEN 'OLD ORDER'
	ELSE 'NEW ORDER'
	END AS ORDER_STATUS
FROM ORDERS;
-- Q4.
-- Display each product with a new column:
-- Electronics → 'Electronic Item'
-- Clothing → 'Fashion Item'
-- Others → 'Other'
-- (Join products and categories.)
SELECT P.PRODUCT_NAME ,
CASE 
   WHEN C.CATEGORY_ID = 1 THEN 'ELECTRONIC ITEM'
   WHEN C.CATEGORY_ID = 2 THEN 'FASHION ITEM'
   ELSE 'OTHER'
   END AS CATEGORIES
FROM CATEGORIES C
JOIN PRODUCTS P
ON C.CATEGORY_ID = P.CATEGORY_ID;


-- Q5.
-- Display each product with:
-- Price > 7000 → 'Premium'
-- Price between 3000 and 7000 → 'Standard'
-- Otherwise → 'Budget'
SELECT PRODUCT_NAME , PRICE ,
CASE
     WHEN PRICE >= 7000 THEN 'PRIMIUM'
	 WHEN PRICE<7000 AND PRICE>3000 THEN 'STANDARD'
	 ELSE 'BUDGET'
	 END AS PRICE_CATEGORY
FROM PRODUCTS;

-- Intermediate (6–10)
-- Q6.
-- Display each customer's total spending and classify them:
-- Above ₹10,000 → 'Gold'
-- ₹5,000–₹10,000 → 'Silver'
-- Below ₹5,000 → 'Bronze'
SELECT SUM(OD.QUANTITY*P.PRICE) , C.CUSTOMER_NAME ,
CASE 
    WHEN SUM(OD.QUANTITY*P.PRICE) >= 10000 THEN 'GOLD'
	WHEN SUM(OD.QUANTITY*P.PRICE) < 10000 AND SUM(OD.QUANTITY*P.PRICE) >= 5000 THEN 'SILVER'
	ELSE 'BRONZE'
	END AS CUSTOMER_REWARD
FROM PRODUCTS P
JOIN ORDER_DETAILS OD
ON P.PRODUCT_ID = OD.PRODUCT_ID
JOIN ORDERS O
ON O.ORDER_ID = OD.ORDER_ID 
JOIN CUSTOMERS C
ON C.CUSTOMER_ID = O.CUSTOMER_ID 
GROUP BY C.CUSTOMER_NAME;
-- Q7.
-- Display each category's total revenue and classify:
-- Revenue > ₹20,000 → 'High Revenue'
-- Otherwise → 'Low Revenue'
SELECT SUM(OD.QUANTITY*P.PRICE) , C.CATEGORY_NAME ,
CASE 
    WHEN SUM(OD.QUANTITY*P.PRICE) >= 20000 THEN 'HIGH REVENUE'
	ELSE 'LOW REVENUE'
	END AS CATEGORY_REVENUE
FROM PRODUCTS P
JOIN ORDER_DETAILS OD
ON P.PRODUCT_ID = OD.PRODUCT_ID
JOIN ORDERS O
ON O.ORDER_ID = OD.ORDER_ID 
JOIN CATEGORIES C
ON C.CATEGORY_ID = P.CATEGORY_ID
GROUP BY C.CATEGORY_NAME;

-- Q8.
-- Display every order with its total amount and classify:
-- Above ₹8,000 → 'Big Order'
-- Otherwise → 'Small Order'
SELECT SUM(OD.QUANTITY*P.PRICE) , OD.ORDER_ID ,
CASE 
    WHEN SUM(OD.QUANTITY*P.PRICE) >= 8000 THEN 'BIG ORDER'
	ELSE 'SMALL ORDER'
	END AS ORDER_AMOUNT
FROM PRODUCTS P
JOIN ORDER_DETAILS OD
ON P.PRODUCT_ID = OD.PRODUCT_ID
GROUP BY OD.ORDER_ID;

-- Q9.
-- Display products with total quantity sold and classify:
-- More than 20 → 'Best Seller'
-- 10–20 → 'Average Seller'
-- Less than 10 → 'Low Seller'
SELECT SUM(OD.QUANTITY) , P.PRODUCT_NAME,
CASE 
   WHEN SUM(OD.QUANTITY) >= 20 THEN 'BEST SELLER'
   WHEN SUM(OD.QUANTITY) < 20 AND  SUM(OD.QUANTITY)>=10 THEN 'AVERAGE SELLER'
   ELSE 'LOW SELLER'
   END AS PRODUCT_QUANTITY_SOLD
FROM PRODUCTS P
JOIN ORDER_DETAILS OD
ON P.PRODUCT_ID = OD.PRODUCT_ID
GROUP BY P.PRODUCT_NAME;

-- Q10.
-- Display each customer's total number of orders and classify:
-- More than 5 → 'Frequent Customer'
-- Otherwise → 'Regular Customer'
SELECT COUNT(O.ORDER_ID) , C.CUSTOMER_ID ,
CASE 
   WHEN COUNT(O.ORDER_ID) >=5 THEN 'FREQUENT CUSTOMER'
   ELSE 'REGULAR CUSTOMER'
   END AS CUSTOMER_ORDERS
FROM ORDERS O
JOIN CUSTOMERS C
ON O.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID;

-- Interview Level (11–15)
-- Q11.
-- Display every customer's:
-- Name
-- Total Spending
-- Customer Level using CASE:
-- Platinum
-- Gold
-- Silver
-- Bronze
-- (Create your own spending ranges.)
SELECT SUM(OD.QUANTITY*P.PRICE) , C.CUSTOMER_NAME ,
CASE 
    WHEN SUM(OD.QUANTITY*P.PRICE) >= 50000 THEN 'PLATINUM'
	WHEN SUM(OD.QUANTITY*P.PRICE) < 50000 AND SUM(OD.QUANTITY*P.PRICE) >= 25000 THEN 'GOLD'
	WHEN SUM(OD.QUANTITY*P.PRICE) < 25000 AND SUM(OD.QUANTITY*P.PRICE) >= 5000 THEN 'SILVER'
	ELSE 'BRONZE'
	END AS CUSTOMER_REWARD
FROM PRODUCTS P
JOIN ORDER_DETAILS OD
ON P.PRODUCT_ID = OD.PRODUCT_ID
JOIN ORDERS O
ON O.ORDER_ID = OD.ORDER_ID 
JOIN CUSTOMERS C
ON C.CUSTOMER_ID = O.CUSTOMER_ID 
GROUP BY C.CUSTOMER_NAME;

-- Q12.
-- Display each category's:
-- Number of products
-- Category Size:
-- Large
-- Medium
-- Small
-- (Create your own ranges.)
SELECT COUNT(DISTINCT P.PRODUCT_ID) , C.CATEGORY_NAME,
CASE 
   WHEN COUNT(DISTINCT P.PRODUCT_ID) > 5 THEN 'LARGE'
   WHEN COUNT(DISTINCT P.PRODUCT_ID) <=5 AND COUNT(DISTINCT P.PRODUCT_ID) > 3 THEN 'MEDIUM'
   ELSE 'SMALL'
   END AS CATEGORY_SIZES
FROM PRODUCTS P
JOIN CATEGORIES C
ON P.CATEGORY_ID = C.CATEGORY_ID 
JOIN ORDER_DETAILS OD
ON P.PRODUCT_ID = OD.PRODUCT_ID
GROUP BY C.CATEGORY_NAME ;
-- Q13.
-- Display every product with:
-- Revenue
-- Revenue Status:
-- High
-- Medium
-- Low
SELECT SUM(OD.QUANTITY*P.PRICE) , P.PRODUCT_NAME,
CASE 
    WHEN SUM(OD.QUANTITY*P.PRICE) >= 8000 THEN 'HIGH'
	WHEN SUM(OD.QUANTITY*P.PRICE) < 8000 AND SUM(OD.QUANTITY*P.PRICE) >=3000 THEN 'MEDIUM'
	ELSE 'LOW'
	END AS PRODUCT_REVENUE
FROM PRODUCTS P
JOIN ORDER_DETAILS OD
ON P.PRODUCT_ID = OD.PRODUCT_ID
GROUP BY P.PRODUCT_NAME;

-- Q14.
-- Display each city with:
-- Total Revenue
-- Performance:
-- Excellent
-- Good
-- Average
SELECT SUM(OD.QUANTITY*P.PRICE) , C.CITY,
CASE 
    WHEN SUM(OD.QUANTITY*P.PRICE) >= 80000 THEN 'EXCELLENT'
	WHEN SUM(OD.QUANTITY*P.PRICE) < 80000 AND SUM(OD.QUANTITY*P.PRICE) >=30000 THEN 'GOOD'
	ELSE 'AVERAGE'
	END AS CITY_REVENUE
FROM PRODUCTS P
JOIN ORDER_DETAILS OD
ON P.PRODUCT_ID = OD.PRODUCT_ID
JOIN ORDERS O
ON O.ORDER_ID = OD.ORDER_ID 
JOIN CUSTOMERS C
ON C.CUSTOMER_ID = O.CUSTOMER_ID 
GROUP BY C.CITY
-- Q15.
-- Display each customer and show:
-- Total Quantity Purchased
-- Shopping Habit:
-- Heavy Buyer
-- Medium Buyer
-- Light Buyer
SELECT SUM(OD.QUANTITY) , C.CUSTOMER_NAME ,
CASE 
   WHEN SUM(OD.QUANTITY) >= 5 THEN 'HEAVY BUYER'
   WHEN SUM(OD.QUANTITY) <= 5 AND SUM(OD.QUANTITY) > 3 THEN 'MEDIUM BUYER'
   ELSE 'LIGHT BUYER'
   END AS CUSTOMER_STATUS 
FROM CUSTOMERS C
JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID 
JOIN ORDER_DETAILS OD
ON O.ORDER_ID = OD.ORDER_ID
GROUP BY C.CUSTOMER_NAME;

-- Part B – Revision Questions (Previous Concepts)
-- Q16.
-- Display the top 3 customers based on revenue.
SELECT SUM(OD.QUANTITY*P.PRICE) AS REVENUE, C.CUSTOMER_NAME
FROM ORDER_DETAILS OD 
JOIN PRODUCTS P
ON P.PRODUCT_ID = OD.PRODUCT_ID 
JOIN ORDERS O
ON O.ORDER_ID = OD.ORDER_ID
JOIN CUSTOMERS C
ON C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY C.CUSTOMER_NAME 
ORDER BY SUM(OD.QUANTITY*P.PRICE) DESC
LIMIT 3;

-- Q17.
-- Display the product with the highest average quantity ordered.
SELECT ROUND(AVG(OD.QUANTITY),1) , P.PRODUCT_NAME 
FROM ORDER_DETAILS OD
JOIN PRODUCTS P
ON P.PRODUCT_ID = OD.PRODUCT_ID 
GROUP BY P.PRODUCT_NAME 
ORDER BY ROUND(AVG(OD.QUANTITY),1) DESC
LIMIT 1;

-- Q18.
-- Display each category's:
-- Total products
-- Average product price
-- Maximum product price
SELECT COUNT(P.PRODUCT_ID) AS TOTAL_PRODUCT , MAX(P.PRICE) AS MAXIMUM_PRICE , AVG(P.PRICE) AS AVERAGE_PRICE, C.CATEGORY_NAME
FROM CATEGORIES C 
JOIN PRODUCTS P
ON P.CATEGORY_ID  = C.CATEGORY_ID
GROUP BY C.CATEGORY_NAME;

-- Q19.
-- Display customers who purchased products from more than one category.
-- Hint: Use COUNT(DISTINCT category_id).
SELECT COUNT(DISTINCT CG.CATEGORY_ID) , C.CUSTOMER_NAME 
FROM ORDER_DETAILS OD 
JOIN PRODUCTS P
ON P.PRODUCT_ID = OD.PRODUCT_ID 
JOIN ORDERS O
ON O.ORDER_ID = OD.ORDER_ID
JOIN CUSTOMERS C
ON C.CUSTOMER_ID = O.CUSTOMER_ID
JOIN CATEGORIES CG
ON P.CATEGORY_ID = CG.CATEGORY_ID
GROUP BY C.CUSTOMER_NAME
HAVING  COUNT(DISTINCT CG.CATEGORY_ID) > 1;


-- Q20.
-- Display the month that generated the highest revenue.
-- Hint: Use:
-- EXTRACT(MONTH FROM order_date)
-- SUM(quantity × price)
-- GROUP BY
-- ORDER BY
SELECT SUM(OD.QUANTITY*P.PRICE) , EXTRACT(MONTH FROM O.ORDER_DATE)
FROM ORDER_DETAILS OD 
JOIN PRODUCTS P
ON P.PRODUCT_ID = OD.PRODUCT_ID 
JOIN ORDERS O
ON O.ORDER_ID = OD.ORDER_ID
GROUP BY  EXTRACT(MONTH FROM O.ORDER_DATE)
ORDER BY SUM(OD.QUANTITY*P.PRICE) DESC
LIMIT 1;
